### ISSUE TITLE
微信小程序开发者工具，只有点击审查元素时才能看到元素

### ISSUE THREAD

**Issue by lijunlin2022** [lijunlin2022/bug#15]
## 问题描述

如下图所示，微信开发者工具，只有当我点击审查元素时，才能够在模拟器上看到图片。

![](https://raw.githubusercontent.com/lijunlin2022/bug/main/2023-03-21-20-53-56.gif)

选择 2.30.2、2.30.0、2.25.4、2.24.4 甚至更低版本的基础库都有问题。

## 复现代码

- wxml

```html
<view class="container">
  <scroll-view scroll-x="{{true}}" enable-flex="{{true}}" class="inner">
    <view wx:for="{{2}}" wx:key="item">
      <view class="img-box">
        <image src="https://avatars.githubusercontent.com/u/60834609?v=4" />
        <view class="img-cover" />
      </view>
    </view>
  </scroll-view>
</view>
```

- wxss

```css
.container {
  border-radius: 1rpx;
  overflow: hidden;
}

.inner {
  display: flex;
}

.img-box {
  position: relative;
  border-radius: 1rpx;
  overflow: hidden;
}

.img-cover {
  position: absolute;
}
```

## 解决办法

这是一个微信开发者工具的 Bug，把微信开发者工具升级到 1.06.2303060darwin-x64 即可解决。
