### ISSUE TITLE
倒计时闪动问题

### ISSUE THREAD

**Issue by lijunlin2022** [lijunlin2022/bug#3]
## 现象

页面有倒计时元素时，因为每个数字的宽度不同，偶尔会看到倒计时闪动。

比如 20:00:01 变成 20:00:00 时，因为 1 的宽度比 0 窄，所以会闪动一下。

## 解决办法

有两种办法可以解决这个问题：

1. 可以给标签设置一个固定宽度，并让标签中的文字居左。

```css
.text {
  width: 135px;
  text-align: left;
}
```

2. 可以将文字设置为等宽字体

```css
.text {
  font-family: monospace;
}
```
