### ISSUE TITLE
Chrome 浏览器不支持小于 12px 以下的字体，手机浏览器不支持小于 8px 以下的字体

### ISSUE THREAD

**Issue by lijunlin2022** [lijunlin2022/bug#5]
## 现象

在 Chrome 浏览器中，如果设置的 font-size 小于 12px，那么浏览器显示的还是 12px 的字体。

在手机浏览器中，如果设置的 font-size 小于 8px，那么浏览器还是的还是 8px 的字体。

## 解决办法

利用 transform 中的 scale 缩小属性。

```css
.text {
  transfrom: scale(0.8);
}
```
